language: python
env:
  matrix:
    - TOXENV="py35"
    - TOXENV="py36"
install:
  - pip install tox
# before_script:
#   - pep8 --ignore=E501,E225,E123 django_spaghetti 
#   - cd docs ; sphinx-build -nW -b html -d _build/doctrees . _build/html ; cd ..
# command to run tests
script:
  - tox -e $TOXENV
after_success:
  - coveralls
  